/********************************************************************
* /input/FairShipRun/genfit/fieldsRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /input/FairShipRun/genfit/fieldsRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablefieldsRootDict();
extern void G__cpp_setup_inheritancefieldsRootDict();
extern void G__cpp_setup_typetablefieldsRootDict();
extern void G__cpp_setup_memvarfieldsRootDict();
extern void G__cpp_setup_globalfieldsRootDict();
extern void G__cpp_setup_memfuncfieldsRootDict();
extern void G__cpp_setup_funcfieldsRootDict();
extern void G__set_cpp_environmentfieldsRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/input/FairShip/genfit/fields/include/ConstField.h"
#include "/input/FairShip/genfit/fields/include/BellField.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fieldsRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__fieldsRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fieldsRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__fieldsRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__fieldsRootDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__fieldsRootDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__fieldsRootDictLN_TVector3;
extern G__linked_taginfo G__fieldsRootDictLN_genfit;
extern G__linked_taginfo G__fieldsRootDictLN_genfitcLcLAbsBField;
extern G__linked_taginfo G__fieldsRootDictLN_genfitcLcLConstField;
extern G__linked_taginfo G__fieldsRootDictLN_genfitcLcLBellField;

/* STUB derived class for protected member access */
