//
// File generated by /opt/ocean/FairSoftInst/bin/rootcint at Thu Oct  8 06:27:25 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dIinputdIFairShipRundIgenfitdIGBLRootDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GBLRootDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void genfitcLcLGFGbl_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_genfitcLcLGFGbl(void *p = 0);
   static void *newArray_genfitcLcLGFGbl(Long_t size, void *p);
   static void delete_genfitcLcLGFGbl(void *p);
   static void deleteArray_genfitcLcLGFGbl(void *p);
   static void destruct_genfitcLcLGFGbl(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::genfit::GFGbl*)
   {
      ::genfit::GFGbl *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::genfit::GFGbl >(0);
      static ::ROOT::TGenericClassInfo 
         instance("genfit::GFGbl", ::genfit::GFGbl::Class_Version(), "/input/FairShip/genfit/GBL/include/GFGbl.h", 48,
                  typeid(::genfit::GFGbl), ::ROOT::DefineBehavior(ptr, ptr),
                  &::genfit::GFGbl::Dictionary, isa_proxy, 4,
                  sizeof(::genfit::GFGbl) );
      instance.SetNew(&new_genfitcLcLGFGbl);
      instance.SetNewArray(&newArray_genfitcLcLGFGbl);
      instance.SetDelete(&delete_genfitcLcLGFGbl);
      instance.SetDeleteArray(&deleteArray_genfitcLcLGFGbl);
      instance.SetDestructor(&destruct_genfitcLcLGFGbl);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::genfit::GFGbl*)
   {
      return GenerateInitInstanceLocal((::genfit::GFGbl*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::genfit::GFGbl*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

      namespace genfit {
//______________________________________________________________________________
atomic_TClass_ptr GFGbl::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *GFGbl::Class_Name()
{
   return "genfit::GFGbl";
}

//______________________________________________________________________________
const char *GFGbl::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::genfit::GFGbl*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GFGbl::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::genfit::GFGbl*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GFGbl::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::genfit::GFGbl*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GFGbl::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::genfit::GFGbl*)0x0)->GetClass();} }
   return fgIsA;
}

} // namespace genfit
      namespace genfit {
//______________________________________________________________________________
void GFGbl::Streamer(TBuffer &R__b)
{
   // Stream an object of class genfit::GFGbl.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(genfit::GFGbl::Class(),this);
   } else {
      R__b.WriteClassBuffer(genfit::GFGbl::Class(),this);
   }
}

} // namespace genfit
//______________________________________________________________________________
      namespace genfit {
void GFGbl::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class genfit::GFGbl.
      TClass *R__cl = ::genfit::GFGbl::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_milleFileName", (void*)&m_milleFileName);
      R__insp.InspectMember("string", (void*)&m_milleFileName, "m_milleFileName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_gblInternalIterations", (void*)&m_gblInternalIterations);
      R__insp.InspectMember("string", (void*)&m_gblInternalIterations, "m_gblInternalIterations.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_pValueCut", &m_pValueCut);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_minNdf", &m_minNdf);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_chi2Cut", &m_chi2Cut);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_enableScatterers", &m_enableScatterers);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_enableIntermediateScatterer", &m_enableIntermediateScatterer);
      R__insp.GenericShowMembers("genfit::AbsFitter", ( ::genfit::AbsFitter *) (this ), false);
}

} // namespace genfit
namespace ROOTDict {
   // Wrappers around operator new
   static void *new_genfitcLcLGFGbl(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genfit::GFGbl : new ::genfit::GFGbl;
   }
   static void *newArray_genfitcLcLGFGbl(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::genfit::GFGbl[nElements] : new ::genfit::GFGbl[nElements];
   }
   // Wrapper around operator delete
   static void delete_genfitcLcLGFGbl(void *p) {
      delete ((::genfit::GFGbl*)p);
   }
   static void deleteArray_genfitcLcLGFGbl(void *p) {
      delete [] ((::genfit::GFGbl*)p);
   }
   static void destruct_genfitcLcLGFGbl(void *p) {
      typedef ::genfit::GFGbl current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::genfit::GFGbl

/********************************************************
* /input/FairShipRun/genfit/GBLRootDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGBLRootDict();

extern "C" void G__set_cpp_environmentGBLRootDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("/input/FairShip/genfit/GBL/include/GFGbl.h");
  G__cpp_reset_tagtableGBLRootDict();
}
#include <new>
extern "C" int G__cpp_dllrevGBLRootDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* genfit::GFGbl */
static int G__GBLRootDict_621_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   genfit::GFGbl* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genfit::GFGbl[n];
     } else {
       p = new((void*) gvp) genfit::GFGbl[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new genfit::GFGbl;
     } else {
       p = new((void*) gvp) genfit::GFGbl;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLGFGbl));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genfit::GFGbl*) G__getstructoffset())->beginRun();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genfit::GFGbl*) G__getstructoffset())->endRun();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((genfit::GFGbl*) G__getstructoffset())->setGBLOptions(*((string*) G__int(libp->para[0])), (bool) G__int(libp->para[1])
, (bool) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((genfit::GFGbl*) G__getstructoffset())->setGBLOptions(*((string*) G__int(libp->para[0])), (bool) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((genfit::GFGbl*) G__getstructoffset())->setGBLOptions(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      ((genfit::GFGbl*) G__getstructoffset())->setGBLOptions();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ((genfit::GFGbl*) G__getstructoffset())->setMP2Options((double) G__double(libp->para[0]), (unsigned int) G__int(libp->para[1])
, *((string*) G__int(libp->para[2])), (double) G__double(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((genfit::GFGbl*) G__getstructoffset())->setMP2Options((double) G__double(libp->para[0]), (unsigned int) G__int(libp->para[1])
, *((string*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      ((genfit::GFGbl*) G__getstructoffset())->setMP2Options((double) G__double(libp->para[0]), (unsigned int) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((genfit::GFGbl*) G__getstructoffset())->setMP2Options((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((genfit::GFGbl*) G__getstructoffset())->setMP2Options();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) genfit::GFGbl::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) genfit::GFGbl::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) genfit::GFGbl::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      genfit::GFGbl::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const genfit::GFGbl*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genfit::GFGbl*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genfit::GFGbl*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((genfit::GFGbl*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) genfit::GFGbl::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) genfit::GFGbl::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) genfit::GFGbl::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GBLRootDict_621_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) genfit::GFGbl::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef genfit::GFGbl G__TgenfitcLcLGFGbl;
static int G__GBLRootDict_621_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (genfit::GFGbl*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((genfit::GFGbl*) (soff+(sizeof(genfit::GFGbl)*i)))->~G__TgenfitcLcLGFGbl();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (genfit::GFGbl*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((genfit::GFGbl*) (soff))->~G__TgenfitcLcLGFGbl();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* genfit::GFGbl */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGBLRootDict {
 public:
  G__Sizep2memfuncGBLRootDict(): p(&G__Sizep2memfuncGBLRootDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGBLRootDict::*p)();
};

size_t G__get_sizep2memfuncGBLRootDict()
{
  G__Sizep2memfuncGBLRootDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGBLRootDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLGFGbl))) {
     genfit::GFGbl *G__Lderived;
     G__Lderived=(genfit::GFGbl*)0x1000;
     {
       genfit::AbsFitter *G__Lpbase=(genfit::AbsFitter*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLGFGbl),G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLAbsFitter),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGBLRootDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO2gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVector<double,2*(2+1)/2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO3gR),0,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMath));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2,2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO2gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2,3>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVector<double,2*(3+1)/2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO4gR),0,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMath));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2,5>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO5gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVector<double,2*(5+1)/2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO6gR),0,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMath));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO5gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2,7>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO7cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO7gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVector<double,2*(7+1)/2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO8gR),0,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMath));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO7cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO7gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,3,2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO2gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVector<double,3*(2+1)/2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO4gR),0,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMath));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,3>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO2gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,3>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVector<double,3*(3+1)/2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO6gR),0,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMath));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,3,3>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO3gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,5>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO5cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO5cO5gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("SVector<double,5*(5+1)/2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO15gR),0,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMath));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,5,5>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO5cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO5cO5gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2,5>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO5gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO5gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2,7>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO7cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO7gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,2>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO7cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO7gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,5,5>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO5cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO5cO5gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ROOT::Math::SMatrix<double,5>",117,G__get_linked_tagnum(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO5cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO5cO5gRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GblPoint>",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<gbl::GblPoint>",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<std::vector<GblPoint>,TMatrixD>",117,G__get_linked_tagnum(&G__GBLRootDictLN_pairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<vector<GblPoint>,TMatrixD>",117,G__get_linked_tagnum(&G__GBLRootDictLN_pairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<std::vector<GblPoint>,TMatrixD> >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<vector<GblPoint>,TMatrixD> >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<vector<gbl::GblPoint,allocator<gbl::GblPoint> >,TMatrixT<double> > >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<unsigned int> >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<unsigned int> >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<unsigned int,allocator<unsigned int> > >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<GblPoint> >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<GblPoint> >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<gbl::GblPoint,allocator<gbl::GblPoint> > >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<GblData>",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<gbl::GblData>",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixD>",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GBLRootDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixT<double> >",117,G__get_linked_tagnum(&G__GBLRootDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<std::vector<unsigned int>,TMatrixD>",117,G__get_linked_tagnum(&G__GBLRootDictLN_pairlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOTMatrixTlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<vector<unsigned int>,TMatrixD>",117,G__get_linked_tagnum(&G__GBLRootDictLN_pairlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOTMatrixTlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__GBLRootDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* genfit::GFGbl */
static void G__setup_memvargenfitcLcLGFGbl(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLGFGbl));
   { genfit::GFGbl *p; p=(genfit::GFGbl*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GBLRootDictLN_string),-1,-1,4,"m_milleFileName=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GBLRootDictLN_string),-1,-1,4,"m_gblInternalIterations=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_pValueCut=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_minNdf=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"m_chi2Cut=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_enableScatterers=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"m_enableIntermediateScatterer=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GBLRootDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGBLRootDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncgenfitcLcLGFGbl(void) {
   /* genfit::GFGbl */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLGFGbl));
   G__memfunc_setup("GFGbl",418,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLGFGbl), -1, 0, 1, 1, 4, 0, "u 'genfit::GFGbl' - 11 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLGFGbl), -1, 1, 1, 1, 4, 0, "u 'genfit::GFGbl' - 41 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GFGbl",418,G__GBLRootDict_621_0_3, 105, G__get_linked_tagnum(&G__GBLRootDictLN_genfitcLcLGFGbl), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("beginRun",826,G__GBLRootDict_621_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("endRun",620,G__GBLRootDict_621_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setGBLOptions",1293,G__GBLRootDict_621_0_6, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 '\"THC\"' internalIterations g - - 0 'true' enableScatterers "
"g - - 0 'true' enableIntermediateScatterer", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMP2Options",1287,G__GBLRootDict_621_0_7, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - - 0 '0.' pValueCut h - - 0 '1' minNdf "
"u 'string' - 0 '\"millefile.dat\"' mille_file_name d - - 0 '0.' chi2Cut", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("processTrackWithRep",1975,(G__InterfaceMethod) NULL,121, -1, -1, 0, 3, 1, 1, 0, 
"U 'genfit::Track' - 0 - trk U 'genfit::AbsTrackRep' - 10 - rep "
"g - - 0 'false' resortHits", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__GBLRootDict_621_0_9, 85, G__get_linked_tagnum(&G__GBLRootDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&genfit::GFGbl::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GBLRootDict_621_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&genfit::GFGbl::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GBLRootDict_621_0_11, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&genfit::GFGbl::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GBLRootDict_621_0_12, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&genfit::GFGbl::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__GBLRootDict_621_0_13, 85, G__get_linked_tagnum(&G__GBLRootDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__GBLRootDict_621_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__GBLRootDict_621_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GBLRootDict_621_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GBLRootDict_621_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&genfit::GFGbl::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GBLRootDict_621_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&genfit::GFGbl::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GBLRootDict_621_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&genfit::GFGbl::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GBLRootDict_621_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&genfit::GFGbl::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~GFGbl", 544, G__GBLRootDict_621_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGBLRootDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGBLRootDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGBLRootDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GBLRootDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOT = { "ROOT" , 110 , -1 };
G__linked_taginfo G__GBLRootDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMath = { "ROOT::Math" , 110 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO2gRsPgR = { "ROOT::Math::SMatrix<double,2,2,ROOT::Math::MatRepStd<double,2,2> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO3gR = { "ROOT::Math::SVector<double,3>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO3gRsPgR = { "ROOT::Math::SMatrix<double,2,3,ROOT::Math::MatRepStd<double,2,3> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO4gR = { "ROOT::Math::SVector<double,4>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO5gRsPgR = { "ROOT::Math::SMatrix<double,2,5,ROOT::Math::MatRepStd<double,2,5> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO6gR = { "ROOT::Math::SVector<double,6>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO7cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO7gRsPgR = { "ROOT::Math::SMatrix<double,2,7,ROOT::Math::MatRepStd<double,2,7> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO8gR = { "ROOT::Math::SVector<double,8>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO2gRsPgR = { "ROOT::Math::SMatrix<double,3,2,ROOT::Math::MatRepStd<double,3,2> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO3gRsPgR = { "ROOT::Math::SMatrix<double,3,3,ROOT::Math::MatRepStd<double,3,3> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO5cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO5cO5gRsPgR = { "ROOT::Math::SMatrix<double,5,5,ROOT::Math::MatRepStd<double,5,5> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO15gR = { "ROOT::Math::SVector<double,15>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgR = { "vector<gbl::GblPoint,allocator<gbl::GblPoint> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<gbl::GblPoint,allocator<gbl::GblPoint> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_pairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgR = { "pair<vector<gbl::GblPoint,allocator<gbl::GblPoint> >,TMatrixT<double> >" , 115 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgR = { "vector<pair<vector<gbl::GblPoint,allocator<gbl::GblPoint> >,TMatrixT<double> >,allocator<pair<vector<gbl::GblPoint,allocator<gbl::GblPoint> >,TMatrixT<double> > > >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<vector<gbl::GblPoint,allocator<gbl::GblPoint> >,TMatrixT<double> >,allocator<pair<vector<gbl::GblPoint,allocator<gbl::GblPoint> >,TMatrixT<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR = { "vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<unsigned int,allocator<unsigned int> >,allocator<vector<unsigned int,allocator<unsigned int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgR = { "vector<vector<gbl::GblPoint,allocator<gbl::GblPoint> >,allocator<vector<gbl::GblPoint,allocator<gbl::GblPoint> > > >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<gbl::GblPoint,allocator<gbl::GblPoint> >,allocator<vector<gbl::GblPoint,allocator<gbl::GblPoint> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgR = { "vector<gbl::GblData,allocator<gbl::GblData> >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgRcLcLiteratorgR = { "reverse_iterator<vector<gbl::GblData,allocator<gbl::GblData> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR = { "vector<TMatrixT<double>,allocator<TMatrixT<double> > >" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMatrixT<double>,allocator<TMatrixT<double> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_pairlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOTMatrixTlEdoublegRsPgR = { "pair<vector<unsigned int,allocator<unsigned int> >,TMatrixT<double> >" , 115 , -1 };
G__linked_taginfo G__GBLRootDictLN_genfit = { "genfit" , 110 , -1 };
G__linked_taginfo G__GBLRootDictLN_genfitcLcLTrack = { "genfit::Track" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_genfitcLcLAbsTrackRep = { "genfit::AbsTrackRep" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_genfitcLcLAbsFitter = { "genfit::AbsFitter" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__GBLRootDictLN_genfitcLcLGFGbl = { "genfit::GFGbl" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGBLRootDict() {
  G__GBLRootDictLN_TClass.tagnum = -1 ;
  G__GBLRootDictLN_TBuffer.tagnum = -1 ;
  G__GBLRootDictLN_TMemberInspector.tagnum = -1 ;
  G__GBLRootDictLN_ROOT.tagnum = -1 ;
  G__GBLRootDictLN_string.tagnum = -1 ;
  G__GBLRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMath.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO2gRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO3gR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO3gRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO4gR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO5gRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO6gR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO7cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO7gRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO8gR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO2gRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO3gRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO5cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO5cO5gRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO15gR.tagnum = -1 ;
  G__GBLRootDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_vectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_pairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_vectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_vectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_vectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GBLRootDictLN_pairlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOTMatrixTlEdoublegRsPgR.tagnum = -1 ;
  G__GBLRootDictLN_genfit.tagnum = -1 ;
  G__GBLRootDictLN_genfitcLcLTrack.tagnum = -1 ;
  G__GBLRootDictLN_genfitcLcLAbsTrackRep.tagnum = -1 ;
  G__GBLRootDictLN_genfitcLcLAbsFitter.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__GBLRootDictLN_genfitcLcLGFGbl.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGBLRootDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOT);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_string);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMath);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO2gRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO3gR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO3gRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO4gR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO5gRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO6gR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO2cO7cOROOTcLcLMathcLcLMatRepStdlEdoublecO2cO7gRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO8gR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO2cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO2gRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO3cO3cOROOTcLcLMathcLcLMatRepStdlEdoublecO3cO3gRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSMatrixlEdoublecO5cO5cOROOTcLcLMathcLcLMatRepStdlEdoublecO5cO5gRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_ROOTcLcLMathcLcLSVectorlEdoublecO15gR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_pairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRcOallocatorlEpairlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOTMatrixTlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOallocatorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRcOallocatorlEvectorlEgblcLcLGblPointcOallocatorlEgblcLcLGblPointgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlEgblcLcLGblDatacOallocatorlEgblcLcLGblDatagRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_vectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_reverse_iteratorlEvectorlETMatrixTlEdoublegRcOallocatorlETMatrixTlEdoublegRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_pairlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcOTMatrixTlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_genfit);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_genfitcLcLTrack);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_genfitcLcLAbsTrackRep);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_genfitcLcLAbsFitter);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__GBLRootDictLN_TMatrixTSparseDiaglEfloatgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GBLRootDictLN_genfitcLcLGFGbl),sizeof(genfit::GFGbl),-1,265984,(char*)NULL,G__setup_memvargenfitcLcLGFGbl,G__setup_memfuncgenfitcLcLGFGbl);
}
extern "C" void G__cpp_setupGBLRootDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGBLRootDict()");
  G__set_cpp_environmentGBLRootDict();
  G__cpp_setup_tagtableGBLRootDict();

  G__cpp_setup_inheritanceGBLRootDict();

  G__cpp_setup_typetableGBLRootDict();

  G__cpp_setup_memvarGBLRootDict();

  G__cpp_setup_memfuncGBLRootDict();
  G__cpp_setup_globalGBLRootDict();
  G__cpp_setup_funcGBLRootDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGBLRootDict();
  return;
}
class G__cpp_setup_initGBLRootDict {
  public:
    G__cpp_setup_initGBLRootDict() { G__add_setup_func("GBLRootDict",(G__incsetup)(&G__cpp_setupGBLRootDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGBLRootDict() { G__remove_setup_func("GBLRootDict"); }
};
G__cpp_setup_initGBLRootDict G__cpp_setup_initializerGBLRootDict;

