/********************************************************************
* /input/FairShipRun/passive/G__PassiveDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /input/FairShipRun/passive/G__PassiveDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__PassiveDict();
extern void G__cpp_setup_inheritanceG__PassiveDict();
extern void G__cpp_setup_typetableG__PassiveDict();
extern void G__cpp_setup_memvarG__PassiveDict();
extern void G__cpp_setup_globalG__PassiveDict();
extern void G__cpp_setup_memfuncG__PassiveDict();
extern void G__cpp_setup_funcG__PassiveDict();
extern void G__set_cpp_environmentG__PassiveDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ShipCave.h"
#include "ShipGeoCave.h"
#include "ShipMagnet.h"
#include "ShipChamber.h"
#include "ShipTargetStation.h"
#include "ShipMuonShield.h"
#include "ShipPassiveContFact.h"
#include "ShipTAUMagneticSpectrometer.h"
#include "ShipGoliath.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__PassiveDictLN_TClass;
extern G__linked_taginfo G__G__PassiveDictLN_TBuffer;
extern G__linked_taginfo G__G__PassiveDictLN_TMemberInspector;
extern G__linked_taginfo G__G__PassiveDictLN_TObject;
extern G__linked_taginfo G__G__PassiveDictLN_TNamed;
extern G__linked_taginfo G__G__PassiveDictLN_TString;
extern G__linked_taginfo G__G__PassiveDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__G__PassiveDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__G__PassiveDictLN_basic_fstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__G__PassiveDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__PassiveDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__PassiveDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__PassiveDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__PassiveDictLN_FairGeoSet;
extern G__linked_taginfo G__G__PassiveDictLN_FairGeoMedia;
extern G__linked_taginfo G__G__PassiveDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__PassiveDictLN_TGeoVolume;
extern G__linked_taginfo G__G__PassiveDictLN_FairContFact;
extern G__linked_taginfo G__G__PassiveDictLN_FairParSet;
extern G__linked_taginfo G__G__PassiveDictLN_TGeoMedium;
extern G__linked_taginfo G__G__PassiveDictLN_FairModule;
extern G__linked_taginfo G__G__PassiveDictLN_ShipCave;
extern G__linked_taginfo G__G__PassiveDictLN_ShipGeoCave;
extern G__linked_taginfo G__G__PassiveDictLN_maplEintcOTGeoElementRNmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTGeoElementRNmUgRsPgRsPgR;
extern G__linked_taginfo G__G__PassiveDictLN_ShipMagnet;
extern G__linked_taginfo G__G__PassiveDictLN_ShipChamber;
extern G__linked_taginfo G__G__PassiveDictLN_ShipTargetStation;
extern G__linked_taginfo G__G__PassiveDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__G__PassiveDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__PassiveDictLN_TGeoUniformMagField;
extern G__linked_taginfo G__G__PassiveDictLN_ShipMuonShield;
extern G__linked_taginfo G__G__PassiveDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__G__PassiveDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__PassiveDictLN_FairContainer;
extern G__linked_taginfo G__G__PassiveDictLN_ShipPassiveContFact;
extern G__linked_taginfo G__G__PassiveDictLN_ShipTAUMagneticSpectrometer;
extern G__linked_taginfo G__G__PassiveDictLN_ShipGoliath;

/* STUB derived class for protected member access */
