setenv Linux_Flavour_ ""
setenv System_ "x86_64"
source /input/FairShipRun/check_system.csh
if ( "$same_system" == "1" ) then 
  setenv SIMPATH "/opt/ocean/FairSoftInst"
  setenv ROOTSYS "/opt/ocean/FairSoftInst"
  setenv FAIRROOTPATH "/opt/ocean/FairRootInst"
  if ( true == true ) then
    setenv GEANT4_LIBRARY_DIR "/opt/ocean/FairSoftInst/lib"
    setenv GEANT4_INCLUDE_DIR "/opt/ocean/FairSoftInst/include/Geant4:/opt/ocean/FairSoftInst/transport/geant4/source/interfaces/common/include:/opt/ocean/FairSoftInst/transport/geant4/physics_lists/hadronic/Packaging/include:/opt/ocean/FairSoftInst/transport/geant4/physics_lists/hadronic/QGSP/include"
    setenv GEANT4VMC_INCLUDE_DIR "/opt/ocean/FairSoftInst/include/geant4vmc"
    setenv GEANT4VMC_LIBRARY_DIR "/opt/ocean/FairSoftInst/lib"
    setenv GEANT4VMC_MACRO_DIR "/opt/ocean/FairSoftInst/share/geant4_vmc/macro"
    setenv CLHEP_INCLUDE_DIR ""
    setenv CLHEP_LIBRARY_DIR ""
    setenv CLHEP_BASE_DIR ""
    setenv PLUTO_LIBRARY_DIR "/opt/ocean/FairSoftInst/lib"
    setenv PLUTO_INCLUDE_DIR "/opt/ocean/FairSoftInst/include/pluto"
    setenv PYTHIA6_LIBRARY_DIR "/opt/ocean/FairSoftInst/lib"
    setenv G3SYS "/opt/ocean/FairSoftInst/share/geant3"
    setenv GEANT3_INCLUDE_DIR "/opt/ocean/FairSoftInst/include/TGeant3"
    setenv GEANT3_LIBRARY_DIR "/opt/ocean/FairSoftInst/lib"
    setenv GEANT3_LIBRARIES "/opt/ocean/FairSoftInst/lib64/libgeant321.so"
    setenv USE_VGM "1"
    setenv PYTHIA8DATA "/opt/ocean/FairSoftInst/share/pythia8/xmldoc"
    setenv CLASSPATH ""

    setenv G4LEDATA "/opt/ocean/FairSoftInst/share/Geant4/data/G4EMLOW"
    setenv G4LEVELGAMMADATA "/opt/ocean/FairSoftInst/share/Geant4/data/PhotonEvaporation"
    setenv G4NeutronHPCrossSections "/opt/ocean/FairSoftInst/share/Geant4/data/G4NDL"
    setenv G4NEUTRONHPDATA "/opt/ocean/FairSoftInst/share/Geant4/data/G4NDL"
    setenv G4NEUTRONXSDATA "/opt/ocean/FairSoftInst/share/Geant4/data/G4NEUTRONXS"
    setenv G4PIIDATA "/opt/ocean/FairSoftInst/share/Geant4/data/G4PII"
    setenv G4RADIOACTIVEDATA "/opt/ocean/FairSoftInst/share/Geant4/data/RadioactiveDecay"
    setenv G4REALSURFACEDATA "/opt/ocean/FairSoftInst/share/Geant4/data/RealSurface"
    setenv G4SAIDXSDATA "/opt/ocean/FairSoftInst/share/Geant4/data/G4SAIDDATA"
  endif
  setenv ROOT_LIBRARY_DIR "/opt/ocean/FairSoftInst/lib/root"
  setenv ROOT_LIBRARIES "-L/opt/ocean/FairSoftInst/lib/root -lGui -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic"
  setenv ROOT_INCLUDE_DIR "/opt/ocean/FairSoftInst/include/root"
  setenv VMCWORKDIR "/input/FairShip"
  setenv FAIRLIBDIR "/input/FairShipRun/lib"
  setenv PYTHONPATH "/input/FairShip/python:/opt/ocean/FairSoftInst/lib:/opt/ocean/FairSoftInst/lib/root:/opt/ocean/FairSoftInst/lib/Geant4:/opt/ocean/FairSoftInst/lib/g4py"
  setenv DYLD_LIBRARY_PATH ""
  setenv LD_LIBRARY_PATH "/input/FairShipRun/lib:/opt/ocean/FairRootInst/lib:/opt/ocean/FairSoftInst/lib/root:/opt/ocean/FairSoftInst/lib"
  setenv PATH "/opt/ocean/FairSoftInst/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
endif
