export Linux_Flavour_=""
export System_="x86_64"
source /input/FairShipRun/check_system.sh                               
if [ "$same_system" == "1" ]; then 
  export SIMPATH="/opt/ocean/FairSoftInst"
  export ROOTSYS="/opt/ocean/FairSoftInst"
  export FAIRROOTPATH="/opt/ocean/FairRootInst"
  if (true); then
    export GEANT4_LIBRARY_DIR="/opt/ocean/FairSoftInst/lib"
    export GEANT4_INCLUDE_DIR="/opt/ocean/FairSoftInst/include/Geant4:/opt/ocean/FairSoftInst/transport/geant4/source/interfaces/common/include:/opt/ocean/FairSoftInst/transport/geant4/physics_lists/hadronic/Packaging/include:/opt/ocean/FairSoftInst/transport/geant4/physics_lists/hadronic/QGSP/include"
    export GEANT4VMC_INCLUDE_DIR="/opt/ocean/FairSoftInst/include/geant4vmc"
    export GEANT4VMC_LIBRARY_DIR="/opt/ocean/FairSoftInst/lib"
    export GEANT4VMC_MACRO_DIR="/opt/ocean/FairSoftInst/share/geant4_vmc/macro"
    export CLHEP_INCLUDE_DIR=""
    export CLHEP_LIBRARY_DIR=""
    export CLHEP_BASE_DIR=""
    export PLUTO_LIBRARY_DIR="/opt/ocean/FairSoftInst/lib"
    export PLUTO_INCLUDE_DIR="/opt/ocean/FairSoftInst/include/pluto"
    export PYTHIA6_LIBRARY_DIR="/opt/ocean/FairSoftInst/lib"
    export G3SYS="/opt/ocean/FairSoftInst/share/geant3"
    export GEANT3_INCLUDE_DIR="/opt/ocean/FairSoftInst/include/TGeant3"
    export GEANT3_LIBRARY_DIR="/opt/ocean/FairSoftInst/lib"
    export GEANT3_LIBRARIES="/opt/ocean/FairSoftInst/lib64/libgeant321.so"
    export USE_VGM="1"
    export PYTHIA8DATA="/opt/ocean/FairSoftInst/share/pythia8/xmldoc"
    export CLASSPATH=""

    export G4LEDATA="/opt/ocean/FairSoftInst/share/Geant4/data/G4EMLOW"
    export G4LEVELGAMMADATA="/opt/ocean/FairSoftInst/share/Geant4/data/PhotonEvaporation"
    export G4NeutronHPCrossSections="/opt/ocean/FairSoftInst/share/Geant4/data/G4NDL"
    export G4NEUTRONHPDATA="/opt/ocean/FairSoftInst/share/Geant4/data/G4NDL"
    export G4NEUTRONXSDATA="/opt/ocean/FairSoftInst/share/Geant4/data/G4NEUTRONXS"
    export G4PIIDATA="/opt/ocean/FairSoftInst/share/Geant4/data/G4PII"
    export G4RADIOACTIVEDATA="/opt/ocean/FairSoftInst/share/Geant4/data/RadioactiveDecay"
    export G4REALSURFACEDATA="/opt/ocean/FairSoftInst/share/Geant4/data/RealSurface"
    export G4SAIDXSDATA="/opt/ocean/FairSoftInst/share/Geant4/data/G4SAIDDATA"
  fi
  export ROOT_LIBRARY_DIR="/opt/ocean/FairSoftInst/lib/root"
  export ROOT_LIBRARIES="-L/opt/ocean/FairSoftInst/lib/root -lGui -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic"
  export ROOT_INCLUDE_DIR="/opt/ocean/FairSoftInst/include/root"
  export VMCWORKDIR="/input/FairShip"
  export FAIRLIBDIR="/input/FairShipRun/lib"
  export PYTHONPATH="/input/FairShip/python:/opt/ocean/FairSoftInst/lib:/opt/ocean/FairSoftInst/lib/root:/opt/ocean/FairSoftInst/lib/Geant4:/opt/ocean/FairSoftInst/lib/g4py"
  export DYLD_LIBRARY_PATH=""
  export LD_LIBRARY_PATH="/input/FairShipRun/lib:/opt/ocean/FairRootInst/lib:/opt/ocean/FairSoftInst/lib/root:/opt/ocean/FairSoftInst/lib"
  export PATH="/opt/ocean/FairSoftInst/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
fi
