/********************************************************************
* /input/FairShipRun/shipdata/G__ShipDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /input/FairShipRun/shipdata/G__ShipDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__ShipDataDict();
extern void G__cpp_setup_inheritanceG__ShipDataDict();
extern void G__cpp_setup_typetableG__ShipDataDict();
extern void G__cpp_setup_memvarG__ShipDataDict();
extern void G__cpp_setup_globalG__ShipDataDict();
extern void G__cpp_setup_memfuncG__ShipDataDict();
extern void G__cpp_setup_funcG__ShipDataDict();
extern void G__set_cpp_environmentG__ShipDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ShipStack.h"
#include "ShipMCTrack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__ShipDataDictLN_TClass;
extern G__linked_taginfo G__G__ShipDataDictLN_TBuffer;
extern G__linked_taginfo G__G__ShipDataDictLN_TMemberInspector;
extern G__linked_taginfo G__G__ShipDataDictLN_TObject;
extern G__linked_taginfo G__G__ShipDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__ShipDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TClonesArray;
extern G__linked_taginfo G__G__ShipDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__ShipDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ShipDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMCProcess;
extern G__linked_taginfo G__G__ShipDataDictLN_TParticle;
extern G__linked_taginfo G__G__ShipDataDictLN_TVirtualMCStack;
extern G__linked_taginfo G__G__ShipDataDictLN_FairLogger;
extern G__linked_taginfo G__G__ShipDataDictLN_TRefArray;
extern G__linked_taginfo G__G__ShipDataDictLN_FairGenericStack;
extern G__linked_taginfo G__G__ShipDataDictLN_DetectorId;
extern G__linked_taginfo G__G__ShipDataDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__G__ShipDataDictLN_pairlEintcOintgR;
extern G__linked_taginfo G__G__ShipDataDictLN_maplEintcOintcOlesslEintgRcOallocatorlEpairlEconstsPintcOintgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__G__ShipDataDictLN_ShipStack;
extern G__linked_taginfo G__G__ShipDataDictLN_dequelETParticlemUcOallocatorlETParticlemUgRsPgR;
extern G__linked_taginfo G__G__ShipDataDictLN_stacklETParticlemUcOdequelETParticlemUcOallocatorlETParticlemUgRsPgRsPgR;
extern G__linked_taginfo G__G__ShipDataDictLN_maplEintcOboolcOlesslEintgRcOallocatorlEpairlEconstsPintcOboolgRsPgRsPgR;
extern G__linked_taginfo G__G__ShipDataDictLN_maplEintcOboolcOlesslEintgRcOallocatorlEpairlEconstsPintcOboolgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__G__ShipDataDictLN_maplEpairlEintcOintgRcOintcOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOintgRsPgRsPgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__G__ShipDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__G__ShipDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__G__ShipDataDictLN_TVector3;
extern G__linked_taginfo G__G__ShipDataDictLN_TLorentzVector;
extern G__linked_taginfo G__G__ShipDataDictLN_ShipMCTrack;

/* STUB derived class for protected member access */
